# Generated by Django 4.1.3 on 2022-11-22 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('websiteLink', models.TextField(blank=True, null=True)),
                ('websiteUser', models.CharField(blank=True, max_length=20, null=True)),
                ('websiteEmail', models.CharField(blank=True, max_length=60, null=True)),
                ('websitePassword', models.CharField(blank=True, max_length=12, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createDate'],
            },
        ),
    ]
